config/routes.rb
Rails.application.routes.draw do
  resources :interactions
  root :to => redirect('/interactions')
  get "pages/about"
  get "pages/contact"
  get "pages/privacy"
  get "pages/terms"

end

app/models/interaction.rb
class Interaction < ActiveRecord::Base
mount_uploader :picture, PictureUploader
geocoded_by :address
after_validation :geocode
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/interactions_controller.rb
class InteractionsController < ApplicationController
  before_action :set_interaction, only: [:show, :edit, :update, :destroy]

  # GET /interactions
  # GET /interactions.json
  def index
    @interactions = Interaction.all
    @markers = Gmaps4rails.build_markers(@interactions) do |interaction, marker|
      marker.lat interaction.latitude
      marker.lng interaction.longitude
    end
  end

  # GET /interactions/1
  # GET /interactions/1.json
  def show
  end

  # GET /interactions/new
  def new
    @interaction = Interaction.new
  end

  # GET /interactions/1/edit
  def edit
  end

  # POST /interactions
  # POST /interactions.json
  def create
    @interaction = Interaction.new(interaction_params)

    respond_to do |format|
      if @interaction.save
        format.html { redirect_to @interaction, notice: 'Interaction was successfully created.' }
        format.json { render :show, status: :created, location: @interaction }
      else
        format.html { render :new }
        format.json { render json: @interaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interactions/1
  # PATCH/PUT /interactions/1.json
  def update
    respond_to do |format|
      if @interaction.update(interaction_params)
        format.html { redirect_to @interaction, notice: 'Interaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @interaction }
      else
        format.html { render :edit }
        format.json { render json: @interaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interactions/1
  # DELETE /interactions/1.json
  def destroy
    @interaction.destroy
    respond_to do |format|
      format.html { redirect_to interactions_url, notice: 'Interaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_interaction
      @interaction = Interaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def interaction_params
      params.require(:interaction).permit(:interaction, :description, :picture, :interactor, :interacted, :address)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  end

  def contact
  end

  def about
  end

  def privacy
  end
  
  def terms
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/interactions_helper.rb
module InteractionsHelper
end

app/views/interactions/_form.html.erb
<%= form_for(@interaction) do |f| %>
  <% if @interaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@interaction.errors.count, "error") %> prohibited this interaction from being saved:</h2>

      <ul>
      <% @interaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :interaction %><br>
    <%= f.text_field :interaction %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="field">
    <%= f.label :interactor %><br>
    <%= f.text_field :interactor %>
  </div>
  <div class="field">
    <%= f.label :interacted %><br>
    <%= f.text_field :interacted %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/interactions/edit.html.erb
<h1>Editing interaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @interaction %> |
<%= link_to 'Back', interactions_path %>

app/views/interactions/index.html.erb
<h1>Listing interactions</h1>
<script type="text/javascript">
  function initialize_map() {
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: {id: 'map'}}, function() {
      raw_markers = <%= raw @markers.to_json %>;
      markers = handler.addMarkers(raw_markers);
      handler.bounds.extendWith(markers);
      handler.getMap().setZoom(4);
      my_center = _.find(raw_markers, function(marker){
        return (marker.lat != null) && (marker.lng != null);});
      handler.getMap().setCenter(my_center);
    });
  }
  google.maps.event.addDomListener(window, "load", initialize_map);
</script>

<div id="map"></div>

<table>
  <thead>
    <tr>
      <th>Interaction</th>
      <th>Description</th>
      <th>Picture</th>
      <th>Interactor</th>
      <th>Interacted</th>
      <th>Address</th>
      <th>Ansehen</th>
      <th>Bearbeiten</th>
      <th>Löschen</th>
    </tr>
  </thead>

  <tbody>
    <% @interactions.each do |interaction| %>
      <tr>
        <td><%= interaction.interaction %></td>
        <td><%= interaction.description %></td>
        <td class ="border"><%= image_tag(interaction.picture_url, :width => 60) if interaction.picture.present? %></td>
        <td><%= interaction.interactor %></td>
        <td><%= interaction.interacted %></td>
        <td><%= interaction.address %></td>
        <td><%= link_to 'XXX', interaction %></td>
        <td><%= link_to 'XXX', edit_interaction_path(interaction) %></td>
        <td><%= link_to 'XXX', interaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Interaction', new_interaction_path %>

app/views/interactions/new.html.erb
<h1>New interaction</h1>

<%= render 'form' %>

<%= link_to 'Back', interactions_path %>

app/views/interactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Interaction:</strong>
  <%= @interaction.interaction %>
</p>

<p>
  <strong>Description:</strong>
  <%= @interaction.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@interaction.picture_url, :width => 300) if @interaction.picture.present? %>
</p>

<p>
  <strong>Interactor:</strong>
  <%= @interaction.interactor %>
</p>

<p>
  <strong>Interacted:</strong>
  <%= @interaction.interacted %>
</p>

<p>
  <strong>Address:</strong>
  <%= @interaction.address %>
</p>

<%= link_to 'Edit', edit_interaction_path(@interaction) %> |
<%= link_to 'Back', interactions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Interact</title>
  <%= javascript_include_tag "//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry" %>
<%= javascript_include_tag "//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="http://railsgirls.com/assets/bootstrap.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <a class="navbar-brand" href="/">The interaction app</a>
    <ul class="nav navbar-nav">
      <li><a href="/interactions">Interactions</a></li>
      <li><a href="/pages/about">About</a></li>
      <li><a href="/pages/contact">Contact</a></li>
      <li><a href="/pages/privacy">Privacy</a></li>
      <li><a href="/pages/terms">Terms</a></li>
    </ul>
  </div>
</div>

<div class="container">
  <%= yield %>
</div>
<footer>
  <div class="navbar-brand">
    BerliNinja 2014 | Ninas App Idea
  </div>
</footer>
</body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Contact Us</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Home Page</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/privacy.html.erb
<h1>Privacy Policy</h1>
<p>Find me in app/views/pages/privacy.html.erb</p>

app/views/pages/terms.html.erb
<h1>Terms of Service</h1>
<p>Find me in app/views/pages/terms.html.erb</p>